### ISSUE TITLE
[Improvement] Change api to output Image instead of json rgb values. 

### ISSUE THREAD

**Issue by wisehackermonkey** [blackspike/pixel-artist#1]
# Hey cool project! found it on reddit.
![image](https://user-images.githubusercontent.com/29699356/107325324-6d690000-6a5e-11eb-8b1d-38cba9cfdba4.png)

I would love to use your api in a personal project. and looked though your code, looks like all the rendering is done client side.
(btw the small little pulse on the loading the images ...so... great!)

# api example:
## input:
`curl https://pixel-artist.herokuapp.com/api/?cols=32&url=https://source.unsplash.com/520x640/?portrait`
### output: 
`A raw img file`

#### i can replace url's in my website with sweet pixelated version!
```html
<img src="https://pixel-artist.herokuapp.com/api/?cols=32&url=https://source.unsplash.com/520x640/?portrait">
```
### Server side rendering probably would be easiest with .svg. not totally sure what's the easiest route.

```
best,
- oran
```

**Comment by blackspike** [comment]
Hey cool glad you like it! I'll have a think about how to do the svg output 🤔

Thanks for the docker stuff and readme tidy!

**Comment by blackspike** [comment]
Done and done – thanks for the idea!

https://github.com/blackspike/pixel-artist#new-svg-api

[Try it out!](https://pixel-artist.herokuapp.com/svg/?shape=square&background=%23bada55&gap=10&size=40&url=https://source.unsplash.com/520x640/?portrait&cols=42)

**Comment by wisehackermonkey** [comment]
![](https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.reactiongifs.com%2Fwp-content%2Fuploads%2F2013%2F02%2Fhappy-dancing.gif&f=1&nofb=1)
# @blackspike  Thanks! this looks great! exactly what I was looking for!


### here is a working example of my profile photo!
<img src="https://user-images.githubusercontent.com/29699356/108644381-95dff980-7463-11eb-850f-138811206504.jpg" width="400">

### im going to test to see if its working in the docker container!

### Im hosting a version on my website should be snappy when vs heroku's 30second boot up.
### [link to hosted on my website live as of 20210221](http://www.orancollins.com:6451/)
<img src="http://www.orancollins.com:6451/svg/?shape=square&background=%23bada55&gap=10&size=40&url=https://avatars.githubusercontent.com/u/29699356?s=460&u=4ac91a851231997782c9e0d378875e92b1db9541&v=4&cols=22&" width="400">

**Comment by blackspike** [comment]
Cool! Glad it's what you wanted :)

Works fast on your server! http://www.orancollins.com:6451/svg/?shape=square&background=%23f00ffgap=2&size=40&url=https://source.unsplash.com/520x640/?portrait&cols=42
